### ISSUE TITLE
Can we make it a standard python Library

### ISSUE THREAD

**Issue by MeNsaaH** [deven96/drive_downloader#2]
A full blown python package and upload it to pypi

**Comment by deven96** [comment]
Definitely now... its doable 
The thing is we might need to add other functionality

**Comment by MeNsaaH** [comment]
We can start by adding a `setup.py` file

**Comment by deven96** [comment]
Yes we can add a simple setup script... I've written several before

**Comment by deven96** [comment]
Done... improvements to follow
